### ISSUE TITLE
打开后没有效果

### ISSUE THREAD

**Issue by wrj2009** [Tim-Fang/Scratch-Addons-for-Aerfaying#1]
Chrome 91.0.4472.114
仅在稽木世界测试
打开插件并设置好之后打开创作页没有任何效果，之后我去改了manifest.json，给每一项包含scratch.mit.edu的列表都加了“https://gitblock.cn/*”，这时VS Code没有显示错误，保存改动之后再删除原来的插件，再导入Chrome，依然没有效果

**Comment by Tim-Fang** [comment]
还没写好呢((((  
这个很迷人 改了url但是不运行
